### ISSUE TITLE
Include the option for URI or UUID by default

### ISSUE THREAD

**Issue by natuk** [isl/3MEditor#2]
At the moment one has to manually upload the generator configuration to include the URI or UUID option. Can this be added by default in the 3M generator options? Perhaps it is specific to RDF but very frequent preference.

```
    <generator name="URIorUUID">
        <custom generatorClass="gr.forth.URIorUUID">
            <set-arg name="text"/>
        </custom>
    </generator>
```

**Comment by group131** [comment]
Do you mean adding URIorUUID to our built-in generators, so that user may simply choose it instead of having to reference it from an uploaded generator policy file?

**Comment by natuk** [comment]
Exactly!

**Comment by group131** [comment]
Scheduled for our next version!

**Comment by group131** [comment]
Added with latest commit ([https://github.com/isl/3MEditor/commit/0f04d3bfa5dfe2affd104cea03fd0e497e70893b](url)) and updated in 3M and 3M-VRE4IC instances (Version: 3.4-SNAPSHOT Build: 2019-04-08 (0f04d3b))
