### ISSUE TITLE
Darwin Core schema is not recognized by 3M

### ISSUE THREAD

**Issue by earnaud** [isl/3MEditor#4]
Hi,

As I was trying your app with a mapping from EML (Ecological Metadata Language) to DwC (Darwin Core), it happened this one was not recognized. A pop-up tells me "undefined" after trying upload the .xsd file matching the DwC schema. 

I don't really know if the issue occurs from your tool or from the .xsd file. I am trying to get in touch with DwC maintainers aside.

EML schema definition can be accessed here: https://github.com/NCEAS/eml/tree/master/xsd 
DwC shema definintion can be accessed here: https://github.com/tdwg/dwc/tree/master/docs/xml

**Comment by earnaud** [comment]
Hello,

do you mean a fake xml document containing the whole possible fields? Ok, I notice this.

Thanks you for this quick answer, it shall close the issue.

**Comment by group131** [comment]
> do you mean a fake xml document containing the whole possible fields? Ok, I notice this.

Exactly.
